### PR TITLE
feat(RangeCalendar): allow non contiguous ranges

### PR DESCRIPTION
**Pull request by epr3**
Hello,

This PR implements a prop on the RangeCalendar/DateRangePicker which allows the selection of dates over unavailable dates following the behaviour described here: https://react-spectrum.adobe.com/react-spectrum/RangeCalendar.html#non-contiguous-ranges

### CODE REVIEW

**Comment by zernonia** [comment]
Yoo @epr3 ! I would like to have feature to be merge to v2 instead of main 😁

**Comment by epr3** [comment]
@zernonia Base branch changed to v2 🚀

**Review by zernonia — APPROVED** [review]
Working pretty well!  Can we quickly add some test case for this? 😁

**Comment by epr3** [comment]
Updated 👍🏻

**Comment by phuclh** [comment]
@epr3 @zernonia can we use this prop in v1?

**Pull request merged**
